version: '3'

services:
  #restapi:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  log-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports: 
      - "41433:1433"
    environment:
     ACCEPT_EULA: "Y"
     SA_PASSWORD: "LudoGameL0ver!"
    volumes:
     - restapi:/var/opt/mssql
    container_name: ludo2
volumes:
  restapi:
    driver: local